# Generated by Django 4.2.5 on 2023-10-06 15:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('email_subject', models.CharField(max_length=68)),
                ('email_body', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pharmacy_name', models.CharField(error_messages={'unique': 'Name already exists.'}, max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Phone number must have at least 10 characters.'), django.core.validators.MaxLengthValidator(limit_value=15, message='Phone number cannot exceed 15 characters.')])),
                ('working_hours_start', models.TimeField(default='08:00')),
                ('working_hours_stop', models.TimeField(default='20:00')),
                ('pharm_img', models.ImageField(default='pharmacy.jpg', upload_to='pharmacy_images/')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_id_number', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(limit_value=7, message='Owner ID must have at least 7 characters.'), django.core.validators.MaxLengthValidator(limit_value=8, message='Owner ID cannot exceed 8 characters.')])),
                ('owner_license', models.CharField(max_length=255, unique=True)),
                ('product_count', models.BigIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0'), message='Rating must be at least 0.0.'), django.core.validators.MaxValueValidator(limit_value=Decimal('5'), message='Rating cannot exceed 5.0.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(default='drug.jpg', upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rate', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
